apiVersion: v1
kind: Service
metadata:
  name: {{ include "registry.fullname" . }}
  labels:
    {{- include "registry.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  {{- if .Values.service.debug }}
  - port: {{ .Values.service.debugPort }}
    targetPort: http
    protocol: TCP
    name: debug
  {{- end }}
  selector:
    {{- include "registry.selectorLabels" . | nindent 4 }}
