{{- if .Values.istio.enabled -}}
{{- $fullName := include "registry.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "registry.fullname" . }}
spec:
  hosts:
  {{- range .Values.istio.hosts }}
  - {{ .host }}
  {{- end }}
  gateways:
  {{- if .Values.istio.gateway.create }}
  - {{ include "registry.fullname" . }}
  {{- else -}}
  - {{ .Values.istio.gateway.name }}
  {{- end }}
  http:
  # {-{- range .Values.istio.hosts }}
  - route:
    - destination:
        host: {{ $fullName }}
        port:
          number: {{ $svcPort }}
  # {{- if .upload }}
  #   match:
  #   - uri:
  #       prefix: {{ .path }}
  #     headers:
  #       Authorization:
  #         {{-  $usernamepassword := printf "%s:%s" .username .password }}
  #         exact: "Basic {{ $usernamepassword | b64enc}}"
  #   timeout: 3s
  # - match:
  #   - uri:
  #       prefix: {{ .path }}
  #   redirect:
  #     authority: {{ $fullName }}
  #     redirectCode: 401
  #   headers:
  #     response:
  #       set:
  #         Www-Authenticate: 'Basic realm="Authentication Required"'
  # {{- end }}         
  # {-{- end }}     
{{- end }}